CREATE DATABASE database02;
USE database02;

ALTER TABLE CUSTOMERS
MODIFY FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
MODIFY Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT chk_age CHECK (Age >= 0);